import React from 'react';
import { AlertTriangle, Boxes, CalendarDays, CheckCircle2, Factory, MessageSquareText, Pencil, Settings, UserX, Zap } from 'lucide-react';
import { FaltaItem, NaoConformidadeItem, ObservacaoItem, ParadaFaltaMaterialItem, ParadaMaquinaItem, ProducaoItem, TipoBobina, User } from '../../types';
import { formatDateBR, formatPotencia } from '../../utils/formatters';
import { Badge, Button, Surface } from '../common/ui';

export type EditableApontamentoStep = 1 | 2 | 3 | 4 | 5 | 6;
interface Props { user: User; selectedDate: string; tipoBobina: TipoBobina | ''; producoes: ProducaoItem[]; paradasFaltaMaterial: ParadaFaltaMaterialItem[]; paradasMaquina: ParadaMaquinaItem[]; naoConformidades: NaoConformidadeItem[]; faltas: FaltaItem[]; observacoes: ObservacaoItem[]; onEditStep: (step: EditableApontamentoStep) => void; productionReadOnly?: boolean; }
interface CardProps { title: string; count: number; icon: React.ReactNode; onEdit: () => void; children: React.ReactNode; actionLabel?: string; }
function ReviewCard({ title, count, icon, onEdit, children, actionLabel = 'Editar' }: CardProps) { return <section className="min-w-0 overflow-hidden rounded-2xl border border-[var(--border-subtle)]"><div className="flex min-h-14 flex-col items-stretch gap-2 border-b border-[var(--border-subtle)] bg-[var(--surface-muted)] px-4 py-3 min-[420px]:flex-row min-[420px]:items-center min-[420px]:justify-between min-[420px]:gap-3"><div className="flex min-w-0 items-center gap-2.5"><span className="shrink-0 text-[var(--text-tertiary)]">{icon}</span><h3 className="min-w-0 flex-1 break-words text-sm font-bold text-[var(--text-primary)] [overflow-wrap:anywhere]">{title}</h3><Badge variant={count > 0 ? 'success' : 'neutral'}>{count}</Badge></div><Button className="w-full min-[420px]:w-auto" variant="ghost" size="sm" leftIcon={<Pencil className="h-3.5 w-3.5" />} onClick={onEdit}>{actionLabel}</Button></div><div className="min-w-0 p-4">{children}</div></section>; }
const Empty = ({ text }: { text: string }) => <p className="text-sm text-[var(--text-tertiary)]">{text}</p>;
const legacyFalta = (item: FaltaItem) => !item.nome && Boolean(item.linha || item.turno || item.quantidade || item.justificativa);

export const ReviewSection: React.FC<Props> = ({ user, selectedDate, tipoBobina, producoes, paradasFaltaMaterial, paradasMaquina, naoConformidades, faltas, observacoes, onEditStep, productionReadOnly = false }) => {
  const totalProducao = producoes.reduce((sum, item) => sum + Number(item.quantidade || 0), 0);
  const totalOcorrencias = paradasFaltaMaterial.length + paradasMaquina.length + naoConformidades.length + faltas.length + observacoes.length;
  return <Surface className="record-industrial overflow-hidden" padding="none"><div className="border-b border-[var(--border-subtle)] p-5 sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><CheckCircle2 className="h-5 w-5" /></span><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--accent)]">Revisão final</p><h2 className="text-lg font-bold text-[var(--text-primary)]">Revisão e envio</h2><p className="mt-1 text-sm leading-6 text-[var(--text-secondary)]">Confira a produção e as ocorrências. Todas as categorias de ocorrência são opcionais.</p></div></div><dl className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-muted)] p-3"><dt className="flex items-center gap-2 text-xs font-semibold uppercase text-[var(--text-tertiary)]"><CalendarDays className="h-4 w-4" />Data</dt><dd className="mt-2 text-sm font-bold text-[var(--text-primary)]">{selectedDate ? formatDateBR(selectedDate) : 'Não selecionada'}</dd></div><div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-muted)] p-3"><dt className="flex items-center gap-2 text-xs font-semibold uppercase text-[var(--text-tertiary)]"><Factory className="h-4 w-4" />Unidade</dt><dd className="mt-2 text-sm font-bold text-[var(--text-primary)]">{user.setor || 'Não definida'}</dd></div><div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-muted)] p-3"><dt className="text-xs font-semibold uppercase text-[var(--text-tertiary)]">{user.setor === 'BOBINA AT/BT' ? 'Tipo de bobina' : 'Ocorrências'}</dt><dd className="mt-2 text-sm font-bold text-[var(--text-primary)]">{user.setor === 'BOBINA AT/BT' ? (tipoBobina || 'Não informado') : totalOcorrencias}</dd></div></dl></div><div className="space-y-4 p-5 sm:p-6">
    <ReviewCard title="Produção" count={producoes.length} icon={<Zap className="h-4 w-4" />} onEdit={() => onEditStep(1)} actionLabel={productionReadOnly ? 'Ver' : 'Editar'}>{producoes.length === 0 ? <Empty text="Nenhum registro de produção." /> : <div className="space-y-2">{producoes.map((item) => <div key={item.id} className="flex flex-wrap justify-between gap-2 rounded-xl bg-[var(--surface-muted)] px-3 py-2.5"><span className="text-sm text-[var(--text-primary)]">{item.linha} · {item.potenciaFormatted || formatPotencia(item.potencia)} kVA{item.turno ? ` · ${item.turno} turno` : ''}</span><strong className="text-sm text-[var(--accent)]">{item.quantidade} unid.</strong></div>)}<p className="text-right text-xs text-[var(--text-secondary)]">Total produzido: <strong>{totalProducao}</strong></p></div>}</ReviewCard>
    <ReviewCard title="Parada por Falta de Material" count={paradasFaltaMaterial.length} icon={<Boxes className="h-4 w-4" />} onEdit={() => onEditStep(2)}>{paradasFaltaMaterial.length === 0 ? <Empty text="Nenhuma parada por falta de material." /> : <div className="space-y-2">{paradasFaltaMaterial.map((item) => <div key={item.id} className="rounded-xl bg-[var(--surface-muted)] px-3 py-2.5"><strong className="text-sm text-[var(--text-primary)]">{item.material}</strong><p className="mt-1 text-sm text-[var(--text-secondary)]">{item.causaMotivo}</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">{item.horaInicio} → {item.horaFim}</p></div>)}</div>}</ReviewCard>
    <ReviewCard title="Parada por Máquina Quebrada" count={paradasMaquina.length} icon={<Settings className="h-4 w-4" />} onEdit={() => onEditStep(3)}>{paradasMaquina.length === 0 ? <Empty text="Nenhuma parada por máquina quebrada." /> : <div className="space-y-2">{paradasMaquina.map((item) => <div key={item.id} className="rounded-xl bg-[var(--surface-muted)] px-3 py-2.5"><strong className="text-sm text-[var(--text-primary)]">{item.maquinaEquipamento}</strong><p className="mt-1 text-sm text-[var(--text-secondary)]">{item.observacao}</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">{item.horaInicio} → {item.horaFim}</p></div>)}</div>}</ReviewCard>
    <ReviewCard title="Não Conformidade" count={naoConformidades.length} icon={<AlertTriangle className="h-4 w-4" />} onEdit={() => onEditStep(4)}>{naoConformidades.length === 0 ? <Empty text="Nenhuma não conformidade." /> : <div className="space-y-2">{naoConformidades.map((item) => <div key={item.id} className="rounded-xl bg-[var(--surface-muted)] px-3 py-2.5"><strong className="text-sm text-[var(--text-primary)]">OP {item.op} · Série {item.numeroSerie}</strong><p className="mt-1 text-sm text-[var(--text-secondary)]">{item.causaNaoConformidade}</p></div>)}</div>}</ReviewCard>
    <ReviewCard title="Faltas" count={faltas.length} icon={<UserX className="h-4 w-4" />} onEdit={() => onEditStep(5)}>{faltas.length === 0 ? <Empty text="Nenhuma falta registrada." /> : <div className="space-y-2">{faltas.map((item) => <div key={item.id} className="rounded-xl bg-[var(--surface-muted)] px-3 py-2.5">{legacyFalta(item) ? <><strong className="text-sm text-[var(--text-primary)]">{item.linha} · {item.turno}</strong><p className="mt-1 text-sm text-[var(--text-secondary)]">Quantidade: {item.quantidade ?? 0}{item.justificativa ? ` · ${item.justificativa}` : ''}</p></> : <><strong className="text-sm text-[var(--text-primary)]">{item.nome}</strong><p className="mt-1 text-xs font-semibold text-[var(--warning)]">{item.turno || 'Turno não informado'}</p><p className="mt-1 text-sm text-[var(--text-secondary)]">{item.motivoJustificativa}</p><p className="mt-1 text-xs text-[var(--text-tertiary)]">Atestado: {item.atestado ? 'Sim' : 'Não'}</p></>}</div>)}</div>}</ReviewCard>
    <ReviewCard title="Observações" count={observacoes.length} icon={<MessageSquareText className="h-4 w-4" />} onEdit={() => onEditStep(6)}>{observacoes.length === 0 ? <Empty text="Nenhuma observação registrada." /> : <div className="space-y-2">{observacoes.map((item) => <div key={item.id} className="rounded-xl bg-[var(--surface-muted)] px-3 py-2.5">{(item.linha || item.turno) && <p className="mb-1 text-xs font-semibold text-[var(--text-tertiary)]">{item.linha ? `Linha ${item.linha}` : ''}{item.linha && item.turno ? ' · ' : ''}{item.turno || ''}</p>}<p className="whitespace-pre-wrap text-sm text-[var(--text-primary)]">{item.observacao}</p>{item.justificativaMeta && <p className="mt-2 text-sm text-[var(--text-secondary)]"><strong>Justificativa da meta:</strong> {item.justificativaMeta}</p>}</div>)}</div>}</ReviewCard>
  </div></Surface>;
};
